### YamlMime:ManagedReference
items:
- uid: IdeaStatiCa.Plugin.IAutomation
  commentId: T:IdeaStatiCa.Plugin.IAutomation
  id: IAutomation
  parent: IdeaStatiCa.Plugin
  children:
  - IdeaStatiCa.Plugin.IAutomation.CloseProject
  - IdeaStatiCa.Plugin.IAutomation.NotifyChange
  - IdeaStatiCa.Plugin.IAutomation.OpenProject(System.String)
  - IdeaStatiCa.Plugin.IAutomation.ProjectDir
  - IdeaStatiCa.Plugin.IAutomation.Refresh
  - IdeaStatiCa.Plugin.IAutomation.RefreshProject
  - IdeaStatiCa.Plugin.IAutomation.SelectItem(System.String)
  - IdeaStatiCa.Plugin.IAutomation.Shutdown
  - IdeaStatiCa.Plugin.IAutomation.Status
  - IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  langs:
  - csharp
  - vb
  name: IAutomation
  nameWithType: IAutomation
  fullName: IdeaStatiCa.Plugin.IAutomation
  type: Interface
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: IAutomation
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 15
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  summary: This interface is used for controlling Idea Statica application from external applictions.
  example: []
  syntax:
    content: >-
      [ServiceContract]

      public interface IAutomation
    content.vb: >-
      <ServiceContract>

      Public Interface IAutomation
  attributes:
  - type: System.ServiceModel.ServiceContractAttribute
    ctor: System.ServiceModel.ServiceContractAttribute.#ctor
    arguments: []
- uid: IdeaStatiCa.Plugin.IAutomation.OpenProject(System.String)
  commentId: M:IdeaStatiCa.Plugin.IAutomation.OpenProject(System.String)
  id: OpenProject(System.String)
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: OpenProject(string)
  nameWithType: IAutomation.OpenProject(string)
  fullName: IdeaStatiCa.Plugin.IAutomation.OpenProject(string)
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: OpenProject
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 22
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  summary: Open <code class="paramref">fileName</code>
  example: []
  syntax:
    content: >-
      [OperationContract]

      void OpenProject(string fileName)
    parameters:
    - id: fileName
      type: System.String
      description: Project to open
    content.vb: >-
      <OperationContract>

      Sub OpenProject(fileName As String)
  overload: IdeaStatiCa.Plugin.IAutomation.OpenProject*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
  nameWithType.vb: IAutomation.OpenProject(String)
  fullName.vb: IdeaStatiCa.Plugin.IAutomation.OpenProject(String)
  name.vb: OpenProject(String)
- uid: IdeaStatiCa.Plugin.IAutomation.SelectItem(System.String)
  commentId: M:IdeaStatiCa.Plugin.IAutomation.SelectItem(System.String)
  id: SelectItem(System.String)
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: SelectItem(string)
  nameWithType: IAutomation.SelectItem(string)
  fullName: IdeaStatiCa.Plugin.IAutomation.SelectItem(string)
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: SelectItem
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 29
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  summary: Select item with <code class="paramref">itemId</code> in the project
  example: []
  syntax:
    content: >-
      [OperationContract]

      void SelectItem(string itemId)
    parameters:
    - id: itemId
      type: System.String
      description: The identifier of the requested item
    content.vb: >-
      <OperationContract>

      Sub SelectItem(itemId As String)
  overload: IdeaStatiCa.Plugin.IAutomation.SelectItem*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
  nameWithType.vb: IAutomation.SelectItem(String)
  fullName.vb: IdeaStatiCa.Plugin.IAutomation.SelectItem(String)
  name.vb: SelectItem(String)
- uid: IdeaStatiCa.Plugin.IAutomation.RefreshProject
  commentId: M:IdeaStatiCa.Plugin.IAutomation.RefreshProject
  id: RefreshProject
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: RefreshProject()
  nameWithType: IAutomation.RefreshProject()
  fullName: IdeaStatiCa.Plugin.IAutomation.RefreshProject()
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: RefreshProject
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 35
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  summary: Refresh the currently open project
  example: []
  syntax:
    content: >-
      [OperationContract]

      void RefreshProject()
    content.vb: >-
      <OperationContract>

      Sub RefreshProject()
  overload: IdeaStatiCa.Plugin.IAutomation.RefreshProject*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
- uid: IdeaStatiCa.Plugin.IAutomation.CloseProject
  commentId: M:IdeaStatiCa.Plugin.IAutomation.CloseProject
  id: CloseProject
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: CloseProject()
  nameWithType: IAutomation.CloseProject()
  fullName: IdeaStatiCa.Plugin.IAutomation.CloseProject()
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: CloseProject
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 41
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  summary: Close the
  example: []
  syntax:
    content: >-
      [OperationContract]

      void CloseProject()
    content.vb: >-
      <OperationContract>

      Sub CloseProject()
  overload: IdeaStatiCa.Plugin.IAutomation.CloseProject*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
- uid: IdeaStatiCa.Plugin.IAutomation.Shutdown
  commentId: M:IdeaStatiCa.Plugin.IAutomation.Shutdown
  id: Shutdown
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: Shutdown()
  nameWithType: IAutomation.Shutdown()
  fullName: IdeaStatiCa.Plugin.IAutomation.Shutdown()
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: Shutdown
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 44
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: >-
      [OperationContract]

      void Shutdown()
    content.vb: >-
      <OperationContract>

      Sub Shutdown()
  overload: IdeaStatiCa.Plugin.IAutomation.Shutdown*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
- uid: IdeaStatiCa.Plugin.IAutomation.Refresh
  commentId: M:IdeaStatiCa.Plugin.IAutomation.Refresh
  id: Refresh
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: Refresh()
  nameWithType: IAutomation.Refresh()
  fullName: IdeaStatiCa.Plugin.IAutomation.Refresh()
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: Refresh
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 47
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: >-
      [OperationContract]

      void Refresh()
    content.vb: >-
      <OperationContract>

      Sub Refresh()
  overload: IdeaStatiCa.Plugin.IAutomation.Refresh*
  attributes:
  - type: System.ServiceModel.OperationContractAttribute
    ctor: System.ServiceModel.OperationContractAttribute.#ctor
    arguments: []
- uid: IdeaStatiCa.Plugin.IAutomation.NotifyChange
  commentId: M:IdeaStatiCa.Plugin.IAutomation.NotifyChange
  id: NotifyChange
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: NotifyChange()
  nameWithType: IAutomation.NotifyChange()
  fullName: IdeaStatiCa.Plugin.IAutomation.NotifyChange()
  type: Method
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: NotifyChange
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 50
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: void NotifyChange()
    content.vb: Sub NotifyChange()
  overload: IdeaStatiCa.Plugin.IAutomation.NotifyChange*
- uid: IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  commentId: P:IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  id: TempWorkingDir
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: TempWorkingDir
  nameWithType: IAutomation.TempWorkingDir
  fullName: IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  type: Property
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: TempWorkingDir
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 52
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: string TempWorkingDir { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property TempWorkingDir As String
  overload: IdeaStatiCa.Plugin.IAutomation.TempWorkingDir*
- uid: IdeaStatiCa.Plugin.IAutomation.ProjectDir
  commentId: P:IdeaStatiCa.Plugin.IAutomation.ProjectDir
  id: ProjectDir
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: ProjectDir
  nameWithType: IAutomation.ProjectDir
  fullName: IdeaStatiCa.Plugin.IAutomation.ProjectDir
  type: Property
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: ProjectDir
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 58
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: string ProjectDir { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ProjectDir As String
  overload: IdeaStatiCa.Plugin.IAutomation.ProjectDir*
- uid: IdeaStatiCa.Plugin.IAutomation.Status
  commentId: P:IdeaStatiCa.Plugin.IAutomation.Status
  id: Status
  parent: IdeaStatiCa.Plugin.IAutomation
  langs:
  - csharp
  - vb
  name: Status
  nameWithType: IAutomation.Status
  fullName: IdeaStatiCa.Plugin.IAutomation.Status
  type: Property
  source:
    remote:
      path: src/IdeaStatiCa.Plugin/IAutomation.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: Status
    path: ../src/IdeaStatiCa.Plugin/IAutomation.cs
    startLine: 64
  assemblies:
  - IdeaStatiCa.Plugin
  namespace: IdeaStatiCa.Plugin
  syntax:
    content: AutomationStatus Status { get; }
    parameters: []
    return:
      type: IdeaStatiCa.Plugin.AutomationStatus
    content.vb: ReadOnly Property Status As AutomationStatus
  overload: IdeaStatiCa.Plugin.IAutomation.Status*
references:
- uid: IdeaStatiCa.Plugin
  commentId: N:IdeaStatiCa.Plugin
  href: IdeaStatiCa.html
  name: IdeaStatiCa.Plugin
  nameWithType: IdeaStatiCa.Plugin
  fullName: IdeaStatiCa.Plugin
  spec.csharp:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.Plugin
    name: Plugin
    href: IdeaStatiCa.Plugin.html
  spec.vb:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.Plugin
    name: Plugin
    href: IdeaStatiCa.Plugin.html
- uid: IdeaStatiCa.Plugin.IAutomation.OpenProject*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.OpenProject
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.OpenProject(System.String)
  name: OpenProject
  nameWithType: IAutomation.OpenProject
  fullName: IdeaStatiCa.Plugin.IAutomation.OpenProject
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: IdeaStatiCa.Plugin.IAutomation.SelectItem*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.SelectItem
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.SelectItem(System.String)
  name: SelectItem
  nameWithType: IAutomation.SelectItem
  fullName: IdeaStatiCa.Plugin.IAutomation.SelectItem
- uid: IdeaStatiCa.Plugin.IAutomation.RefreshProject*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.RefreshProject
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.RefreshProject
  name: RefreshProject
  nameWithType: IAutomation.RefreshProject
  fullName: IdeaStatiCa.Plugin.IAutomation.RefreshProject
- uid: IdeaStatiCa.Plugin.IAutomation.CloseProject*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.CloseProject
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.CloseProject
  name: CloseProject
  nameWithType: IAutomation.CloseProject
  fullName: IdeaStatiCa.Plugin.IAutomation.CloseProject
- uid: IdeaStatiCa.Plugin.IAutomation.Shutdown*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.Shutdown
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.Shutdown
  name: Shutdown
  nameWithType: IAutomation.Shutdown
  fullName: IdeaStatiCa.Plugin.IAutomation.Shutdown
- uid: IdeaStatiCa.Plugin.IAutomation.Refresh*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.Refresh
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.Refresh
  name: Refresh
  nameWithType: IAutomation.Refresh
  fullName: IdeaStatiCa.Plugin.IAutomation.Refresh
- uid: IdeaStatiCa.Plugin.IAutomation.NotifyChange*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.NotifyChange
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.NotifyChange
  name: NotifyChange
  nameWithType: IAutomation.NotifyChange
  fullName: IdeaStatiCa.Plugin.IAutomation.NotifyChange
- uid: IdeaStatiCa.Plugin.IAutomation.TempWorkingDir*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
  name: TempWorkingDir
  nameWithType: IAutomation.TempWorkingDir
  fullName: IdeaStatiCa.Plugin.IAutomation.TempWorkingDir
- uid: IdeaStatiCa.Plugin.IAutomation.ProjectDir*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.ProjectDir
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.ProjectDir
  name: ProjectDir
  nameWithType: IAutomation.ProjectDir
  fullName: IdeaStatiCa.Plugin.IAutomation.ProjectDir
- uid: IdeaStatiCa.Plugin.IAutomation.Status*
  commentId: Overload:IdeaStatiCa.Plugin.IAutomation.Status
  href: IdeaStatiCa.Plugin.IAutomation.html#IdeaStatiCa.Plugin.IAutomation.Status
  name: Status
  nameWithType: IAutomation.Status
  fullName: IdeaStatiCa.Plugin.IAutomation.Status
- uid: IdeaStatiCa.Plugin.AutomationStatus
  commentId: T:IdeaStatiCa.Plugin.AutomationStatus
  parent: IdeaStatiCa.Plugin
  href: IdeaStatiCa.Plugin.AutomationStatus.html
  name: AutomationStatus
  nameWithType: AutomationStatus
  fullName: IdeaStatiCa.Plugin.AutomationStatus
