### YamlMime:ManagedReference
items:
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  commentId: T:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  id: ResultsImportersConfiguration
  parent: IdeaStatiCa.BimApiLink
  children:
  - IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter``1(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0})
  - IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  langs:
  - csharp
  - vb
  name: ResultsImportersConfiguration
  nameWithType: ResultsImportersConfiguration
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  type: Class
  source:
    remote:
      path: src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: ResultsImportersConfiguration
    path: ../src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
    startLine: 6
  assemblies:
  - IdeaStatiCa.BimApiLink
  namespace: IdeaStatiCa.BimApiLink
  syntax:
    content: public sealed class ResultsImportersConfiguration
    content.vb: Public NotInheritable Class ResultsImportersConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  commentId: P:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  id: ResultsProvider
  parent: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  langs:
  - csharp
  - vb
  name: ResultsProvider
  nameWithType: ResultsImportersConfiguration.ResultsProvider
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  type: Property
  source:
    remote:
      path: src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: ResultsProvider
    path: ../src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
    startLine: 8
  assemblies:
  - IdeaStatiCa.BimApiLink
  namespace: IdeaStatiCa.BimApiLink
  syntax:
    content: public IBimResultsProvider ResultsProvider { get; }
    parameters: []
    return:
      type: IdeaStatiCa.BimImporter.Results.IBimResultsProvider
    content.vb: Public ReadOnly Property ResultsProvider As IBimResultsProvider
  overload: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider*
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter``1(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0})
  commentId: M:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter``1(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0})
  id: RegisterImporter``1(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0})
  parent: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  langs:
  - csharp
  - vb
  name: RegisterImporter<T>(IInternalForcesImporter<T>)
  nameWithType: ResultsImportersConfiguration.RegisterImporter<T>(IInternalForcesImporter<T>)
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter<T>(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter<T>)
  type: Method
  source:
    remote:
      path: src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
      branch: fix_dev_site_links
      repo: https://github.com/idea-statica/ideastatica-public.git
    id: RegisterImporter
    path: ../src/IdeaStatica.BimApiLink/ResultsImportersConfiguration.cs
    startLine: 12
  assemblies:
  - IdeaStatiCa.BimApiLink
  namespace: IdeaStatiCa.BimApiLink
  syntax:
    content: 'public ResultsImportersConfiguration RegisterImporter<T>(IInternalForcesImporter<T> importer) where T : IIdeaObjectWithResults'
    parameters:
    - id: importer
      type: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{{T}}
    typeParameters:
    - id: T
    return:
      type: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
    content.vb: Public Function RegisterImporter(Of T As IIdeaObjectWithResults)(importer As IInternalForcesImporter(Of T)) As ResultsImportersConfiguration
  overload: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter*
  nameWithType.vb: ResultsImportersConfiguration.RegisterImporter(Of T)(IInternalForcesImporter(Of T))
  fullName.vb: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter(Of T)(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter(Of T))
  name.vb: RegisterImporter(Of T)(IInternalForcesImporter(Of T))
references:
- uid: IdeaStatiCa.BimApiLink
  commentId: N:IdeaStatiCa.BimApiLink
  href: IdeaStatiCa.html
  name: IdeaStatiCa.BimApiLink
  nameWithType: IdeaStatiCa.BimApiLink
  fullName: IdeaStatiCa.BimApiLink
  spec.csharp:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink
    name: BimApiLink
    href: IdeaStatiCa.BimApiLink.html
  spec.vb:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink
    name: BimApiLink
    href: IdeaStatiCa.BimApiLink.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider*
  commentId: Overload:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  href: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.html#IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
  name: ResultsProvider
  nameWithType: ResultsImportersConfiguration.ResultsProvider
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.ResultsProvider
- uid: IdeaStatiCa.BimImporter.Results.IBimResultsProvider
  commentId: T:IdeaStatiCa.BimImporter.Results.IBimResultsProvider
  parent: IdeaStatiCa.BimImporter.Results
  name: IBimResultsProvider
  nameWithType: IBimResultsProvider
  fullName: IdeaStatiCa.BimImporter.Results.IBimResultsProvider
- uid: IdeaStatiCa.BimImporter.Results
  commentId: N:IdeaStatiCa.BimImporter.Results
  name: IdeaStatiCa.BimImporter.Results
  nameWithType: IdeaStatiCa.BimImporter.Results
  fullName: IdeaStatiCa.BimImporter.Results
  spec.csharp:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
  - name: .
  - uid: IdeaStatiCa.BimImporter
    name: BimImporter
  - name: .
  - uid: IdeaStatiCa.BimImporter.Results
    name: Results
  spec.vb:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
  - name: .
  - uid: IdeaStatiCa.BimImporter
    name: BimImporter
  - name: .
  - uid: IdeaStatiCa.BimImporter.Results
    name: Results
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter*
  commentId: Overload:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter
  href: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.html#IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter``1(IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0})
  name: RegisterImporter
  nameWithType: ResultsImportersConfiguration.RegisterImporter
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.RegisterImporter
- uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{{T}}
  commentId: T:IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter{``0}
  parent: IdeaStatiCa.BimApiLink.Results
  definition: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
  href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  name: IInternalForcesImporter<T>
  nameWithType: IInternalForcesImporter<T>
  fullName: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter<T>
  nameWithType.vb: IInternalForcesImporter(Of T)
  fullName.vb: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter(Of T)
  name.vb: IInternalForcesImporter(Of T)
  spec.csharp:
  - uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
    name: IInternalForcesImporter
    href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
    name: IInternalForcesImporter
    href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  commentId: T:IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
  parent: IdeaStatiCa.BimApiLink
  href: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration.html
  name: ResultsImportersConfiguration
  nameWithType: ResultsImportersConfiguration
  fullName: IdeaStatiCa.BimApiLink.ResultsImportersConfiguration
- uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
  commentId: T:IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
  href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  name: IInternalForcesImporter<T>
  nameWithType: IInternalForcesImporter<T>
  fullName: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter<T>
  nameWithType.vb: IInternalForcesImporter(Of T)
  fullName.vb: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter(Of T)
  name.vb: IInternalForcesImporter(Of T)
  spec.csharp:
  - uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
    name: IInternalForcesImporter
    href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter`1
    name: IInternalForcesImporter
    href: IdeaStatiCa.BimApiLink.Results.IInternalForcesImporter-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: IdeaStatiCa.BimApiLink.Results
  commentId: N:IdeaStatiCa.BimApiLink.Results
  href: IdeaStatiCa.html
  name: IdeaStatiCa.BimApiLink.Results
  nameWithType: IdeaStatiCa.BimApiLink.Results
  fullName: IdeaStatiCa.BimApiLink.Results
  spec.csharp:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink
    name: BimApiLink
    href: IdeaStatiCa.BimApiLink.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink.Results
    name: Results
    href: IdeaStatiCa.BimApiLink.Results.html
  spec.vb:
  - uid: IdeaStatiCa
    name: IdeaStatiCa
    href: IdeaStatiCa.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink
    name: BimApiLink
    href: IdeaStatiCa.BimApiLink.html
  - name: .
  - uid: IdeaStatiCa.BimApiLink.Results
    name: Results
    href: IdeaStatiCa.BimApiLink.Results.html
